import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Web3AuthWrapper from "@/components/web3auth";
import { SwitchTheme } from "@/components/DarkMode";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Level Up",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background", inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col">
            <header className="sticky top-0 z-10 flex h-[53px] items-center gap-1 border-b bg-background px-4 shadow-md shadow-zinc-300">
              <h1 className="text-xl font-semibold">Level Up</h1>
              <div className="ml-auto flex">
                <Web3AuthWrapper />
                <SwitchTheme className="gap-1.5" />
              </div>
            </header>
            <main className="flex-1">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
