import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Level Up",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background",inter.className)}>
        <div className="relative flex min-h-dvh flex-col bg-background">
          <Header></Header>
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}



